### ISSUE TITLE
How to add a plugin

### ISSUE THREAD

**Issue by tyeeman** [FooSoft/goldsmith#2]
Yes, looks like a great repo. How to add any of your listed plugins to, for example, your bootstrap demo site.

Update - OK, I see they are in the main.go file. If I want to use tags then I just add them in the meta and it just works?

**Comment by tyeeman** [comment]
I'm trying the bootstrap demo on windows and getting the typical error due to frontslash/backslash fix required. If I change the backslash to frontslash it works.

```
Not Found

The requested URL /blog\post6.html was not found on this server.
```

**Comment by FooSoft** [comment]
Interesting, are you running into that problem with the devserver? I'll fire up a Windows VM and take a look.

**Comment by tyeeman** [comment]
Yes, please try at your end.

**Comment by FooSoft** [comment]
@tyeeman should be fixed by the latest change:
https://github.com/FooSoft/goldsmith/commit/4456f3b206edf4189c9e23ae7a9dcbaf8f616e3f

...and the goldsmith-samples repo has been updated to use the fixed version:
https://github.com/FooSoft/goldsmith-samples/commit/727dc8926eaf923cfb837b01e12e1907ee708fe5

Please reopen if you encounter any more issues.
